### PR TITLE
Added codeql.yml github workflow.

### PR DESCRIPTION
**Pull request by adamhgriffith-uofu**
See #218 for more details.

### CODE REVIEW

**Comment by cnweaver** [comment]
From [the documentation](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/#c-and-c-built-in-support) this looks fairly useless; it doesn't appear to even run something like the clang static analyzer. The only 'vulnerability' it has [detected](https://github.com/slateci/slate-client-server/security/code-scanning/1) is nothing of the sort (I no longer remember why I wanted to overwrite the version field, with what appears in hindsight to be the wrong value, but the comment clearly shows that it was intentional, and it has no security or stability implications).

**Comment by adamhgriffith-uofu** [comment]
Do you have a favorite tool we should use instead?

**Comment by cnweaver** [comment]
It is not clear to me that there is any tool which will usefully perform this job (in no small part because doing the job generally requires solving the halting problem). The clang static analyzer can sometimes detect important code issues, but even then I have gotten only limited value out of it.

**Comment by adamhgriffith-uofu** [comment]
I'll pull this useless thing out then.

**Pull request merged**
