### PR TITLE
Improve cluster info

### PR DESCRIPTION
**Pull request by ike091**
Adds functionality described here: https://github.com/slateci/slate-client-server/issues/132

### CODE REVIEW

**Review by cnweaver — COMMENTED** [review]
At least some of these properties need to be checked for and included only if they exist; for example, not all nodes report a value for 1 GB hugepages allocable/capacity, and neither the API server nor client should not crash if things like that can't be found.

**Comment by ike091** [comment]
Right, I just added checks for all the values

**Comment by Mansalu** [comment]
I think this looks okay now. I still need to test locally. Will you add unit tests to this PR, or include them in a separate one?

**Comment by ike091** [comment]
I'll add unit tests to this PR

**Review by Mansalu — APPROVED** [review]
LGTM

**Pull request merged**
